In [1]:
!pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/22/a5/a0b255295406ed54269814bc93723cfd1a0da63fb9aaf99e1364f07923e5/pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\pycharmprojects\pythonproject1\.venv\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\pycharmprojects\pythonproject1\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/9c/3d/a121f284241f08268b21359bd425f7d4825cffc5ac5cd0e1b3d82ffd2b10/pytz-2024.1-py2.py3-none-any.whl.metadata
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/65/58/f9c9e6be752e9fcb8b6a0ee9fb87e6e7a1f6bcab2cdc73f02bb7ba91ada0/tzdata-2024.1-py2.py3-none-any.whl.metadata
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell\pycharmprojects\pythonproject1\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 1.3 MB/s eta 0:00:09
   ---------------------------------------- 0.1/11.5 MB 762.6 kB/s eta 0:00:15
   ---------------------------------------- 0.1/11.5 MB 1.0 MB/s eta 0:00:12
    --------------------------------------- 0.3/11.5 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.4/11.5 MB 1.5 MB/s eta 0:00:08
   -- ------------------------------------- 0.7/11.5 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 0.9/11.5 MB 2.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/11.5 MB 3.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.7/11.5 MB 3.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/11.5 MB 4.1 MB/s eta 0:00:03
   -------- ------------------------------- 2.5/11.5 MB 4.9 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/11.5 MB 5.4 MB/s eta 0:00:02
   ----------- ---------------------------- 3.2/11.5 MB 5.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.6/11.5 MB 5.6 MB/s eta 0:00:02
   ------------- -------------------------- 3.8/11.5 MB 5.7 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.5 MB 5.7 MB/s eta 0:00:02
   --------------- ------------------------ 4.5/11.5 MB 5.8 MB/s eta 0:00:02
   --------------- ------------------------ 4.6/11.5 MB 5.5 MB/s eta 0:00:02
   ---------------- ----------------------- 4.9/11.5 MB 5.5 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.5 MB 5.7 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 5.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 5.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 5.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 5.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 5.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.5 MB 4.5 MB/s eta 0:00:02
   -------------------- ------------------- 5.9/11.5 MB 4.7 MB/s eta 0:00:02
   --------------------- ------------------ 6.3/11.5 MB 4.8 MB/s eta 0:00:02
   ---------------------- ----------------- 6.5/11.5 MB 4.8 MB/s eta 0:00:02
   ------------------------ --------------- 6.9/11.5 MB 5.0 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.5 MB 5.0 MB/s eta 0:00:01
   -------------------------- ------------- 7.5/11.5 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 7.9/11.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------- ----------- 8.2/11.5 MB 5.2 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 5.2 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.5 MB 5.2 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 5.4 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 10.3/11.5 MB 6.0 MB/s eta 0:00:01
   -------------------------------------- - 10.9/11.5 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 6.1 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ---------------------------------------- 0.0/505.5 kB ? eta -:--:--
   ---------------------- ----------------- 286.7/505.5 kB 8.9 MB/s eta 0:00:01
   ---------------------------------------  501.8/505.5 kB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 505.5/505.5 kB 4.5 MB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ---------------------------------------- 0.0/345.4 kB ? eta -:--:--
   --------------------------------------  337.9/345.4 kB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 345.4/345.4 kB 7.3 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.2 pytz-2024.1 tzdata-2024.1

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd

In [13]:
pd.read_csv('C:/Users/DELL/Desktop/Data/smartphones.csv')

,Smartphone,Brand,Model,RAM,Storage,Color,Free,Final Price
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,279.00
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,179.01
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,279.99
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00
...,...,...,...,...,...,...,...,...
1811,Xiaomi Redmi Note 8 4/64GB Azul Libre,Xiaomi,Redmi Note 8,4.0,64.0,Blue,Yes,249.01
1812,Xiaomi Redmi Note 8T 4/128GB Azul Estelar Libre,Xiaomi,Redmi Note 8T,4.0,128.0,Blue,Yes,200.00
1813,Xiaomi Redmi Note 9 4/128GB Blanco Libre,Xiaomi,Redmi Note 9,4.0,128.0,White,Yes,269.00
1814,Xiaomi Redmi Note 9S 4/64GB Dual SIM Gris Libre,Xiaomi,Note 9S,4.0,64.0,Gray,Yes,211.00
1815,Xiaomi Redmi Note 9S 6/128GB Dual SIM Gris Libre,Xiaomi,Note 9S,6.0,128.0,Gray,Yes,289.00

In [34]:
df=pd.read_csv('C:/Users/DELL/Desktop/Data/smartphones.csv')
df.columns=['Akıllı telefon','Marka','Model','Hafıza','Depolama Alanı','Renk','İndirim','Fiyat']
df

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim,Fiyat
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,279.00
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,179.01
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,279.99
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00
...,...,...,...,...,...,...,...,...
1811,Xiaomi Redmi Note 8 4/64GB Azul Libre,Xiaomi,Redmi Note 8,4.0,64.0,Blue,Yes,249.01
1812,Xiaomi Redmi Note 8T 4/128GB Azul Estelar Libre,Xiaomi,Redmi Note 8T,4.0,128.0,Blue,Yes,200.00
1813,Xiaomi Redmi Note 9 4/128GB Blanco Libre,Xiaomi,Redmi Note 9,4.0,128.0,White,Yes,269.00
1814,Xiaomi Redmi Note 9S 4/64GB Dual SIM Gris Libre,Xiaomi,Note 9S,4.0,64.0,Gray,Yes,211.00
1815,Xiaomi Redmi Note 9S 6/128GB Dual SIM Gris Libre,Xiaomi,Note 9S,6.0,128.0,Gray,Yes,289.00

In [35]:
df.head() #en baştaki satır bilgilerini gösterir

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim,Fiyat
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,279.00
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,179.01
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,279.99
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00

In [36]:
df.tail() #en son satır bilgilerini gösterir

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim,Fiyat
1811,Xiaomi Redmi Note 8 4/64GB Azul Libre,Xiaomi,Redmi Note 8,4.0,64.0,Blue,Yes,249.01
1812,Xiaomi Redmi Note 8T 4/128GB Azul Estelar Libre,Xiaomi,Redmi Note 8T,4.0,128.0,Blue,Yes,200.00
1813,Xiaomi Redmi Note 9 4/128GB Blanco Libre,Xiaomi,Redmi Note 9,4.0,128.0,White,Yes,269.00
1814,Xiaomi Redmi Note 9S 4/64GB Dual SIM Gris Libre,Xiaomi,Note 9S,4.0,64.0,Gray,Yes,211.00
1815,Xiaomi Redmi Note 9S 6/128GB Dual SIM Gris Libre,Xiaomi,Note 9S,6.0,128.0,Gray,Yes,289.00

In [37]:
df.shape #satır ve sütun bilgisi

(1816, 8)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1816 entries, 0 to 1815
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Akıllı telefon  1816 non-null   object
 1   Marka           1816 non-null   object
 2   Model           1816 non-null   object
 3   Hafıza          1333 non-null   float64
 4   Depolama Alanı  1791 non-null   float64
 5   Renk            1816 non-null   object
 6   İndirim         1816 non-null   object
 7   Fiyat           1816 non-null   float64
dtypes: float64(3), object(5)
memory usage: 113.6+ KB

In [40]:
df_yeni=df.drop(['İndirim','Renk'], axis=1)
df_yeni

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Fiyat
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,231.60
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,279.00
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,179.01
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,279.99
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,799.00
...,...,...,...,...,...,...
1811,Xiaomi Redmi Note 8 4/64GB Azul Libre,Xiaomi,Redmi Note 8,4.0,64.0,249.01
1812,Xiaomi Redmi Note 8T 4/128GB Azul Estelar Libre,Xiaomi,Redmi Note 8T,4.0,128.0,200.00
1813,Xiaomi Redmi Note 9 4/128GB Blanco Libre,Xiaomi,Redmi Note 9,4.0,128.0,269.00
1814,Xiaomi Redmi Note 9S 4/64GB Dual SIM Gris Libre,Xiaomi,Note 9S,4.0,64.0,211.00
1815,Xiaomi Redmi Note 9S 6/128GB Dual SIM Gris Libre,Xiaomi,Note 9S,6.0,128.0,289.00

In [48]:
df.drop(['Fiyat'], axis=1, inplace=True)  #fiyatı df üstünden silmiş olduk
df.head()

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim,Puan
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,2048.0
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,512.0
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,512.0
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,768.0
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,6144.0

In [45]:
df['Puan']=df['Hafıza']*df['Depolama Alanı']

In [47]:
df_2000=df[
df['Puan']>2000
]
df_2000

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim,Fiyat,Puan
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,231.60,2048.0
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,799.00,6144.0
6,Nothing Phone (2) 12/256GB Blanco Libre,Nothing,Phone (2),12.0,256.0,White,Yes,699.00,3072.0
9,Xiaomi Redmi Note 12 Pro 8/256GB Gris Grafito ...,Xiaomi,Redmi Note 12,8.0,256.0,Gray,Yes,329.99,2048.0
12,Realme C55 8/256GB Rainy Night Libre,Realme,C55,8.0,256.0,Black,Yes,231.60,2048.0
...,...,...,...,...,...,...,...,...,...
1793,Samsung Galaxy Z Fold4 12/256GB Beige Libre + ...,Samsung,Galaxy Z Fold4,12.0,256.0,White,Yes,1802.94,3072.0
1794,Samsung Galaxy Z Fold4 12/512GB Verde Libre + ...,Samsung,Galaxy Z Fold4,12.0,512.0,Green,Yes,1922.93,6144.0
1796,Xiaomi 11T Pro 5G 8/256GB Blanco Libre,Xiaomi,11T Pro,8.0,256.0,White,Yes,308.01,2048.0
1797,Xiaomi Mi 10 8/256GB Verde Coral Libre,Xiaomi,10,8.0,256.0,Green,Yes,289.00,2048.0
1803,Xiaomi Mi Note 10 Pro 8/256GB Verde Libre,Xiaomi,Mi Note 10,8.0,256.0,Green,Yes,300.72,2048.0

In [50]:
df_puan=df['Puan']
df.drop(['Puan'], axis=1, inplace=True)
df.head()

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes

In [51]:
df_puan

0       2048.0
1        512.0
2        512.0
3        768.0
4       6144.0
         ...
1811     256.0
1812     512.0
1813     512.0
1814     256.0
1815     768.0
Name: Puan, Length: 1816, dtype: float64

In [52]:
pd.concat([df,df_puan])

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim,Puan
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes,NaN
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes,NaN
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes,NaN
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes,NaN
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes,NaN
...,...,...,...,...,...,...,...,...
1811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.0
1812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512.0
1813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512.0
1814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256.0
1815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,768.0

In [53]:
df.describe() #kaç adet veri olduğunu, standart sapmasını, vb bilgileri görüntülemek için

           Hafıza  Depolama Alanı
count  1333.00000     1791.000000
mean      5.96099      162.652150
std       2.66807      139.411605
min       1.00000        2.000000
25%       4.00000       64.000000
50%       6.00000      128.000000
75%       8.00000      256.000000
max      12.00000     1000.000000

In [55]:
df['Hafıza'].mean()  # Ortalama
df['Hafıza'].count()  # Değerlerin sayısı
df['Hafıza'].min()  # En küçük değer
df['Hafıza'].max()  # En büyük değer
df['Hafıza'].sum()  # Toplam
df['Hafıza'].std()  # Standart sapma

2.668069942275087

In [56]:
df

,Akıllı telefon,Marka,Model,Hafıza,Depolama Alanı,Renk,İndirim
0,Realme C55 8/256GB Sunshower Libre,Realme,C55,8.0,256.0,Yellow,Yes
1,Samsung Galaxy M23 5G 4/128GB Azul Libre,Samsung,Galaxy M23,4.0,128.0,Blue,Yes
2,Motorola Moto G13 4/128GB Azul Lavanda Libre,Motorola,Moto G13,4.0,128.0,Blue,Yes
3,Xiaomi Redmi Note 11S 6/128GB Gris Libre,Xiaomi,Redmi Note 11S,6.0,128.0,Gray,Yes
4,Nothing Phone (2) 12/512GB Blanco Libre,Nothing,Phone (2),12.0,512.0,White,Yes
...,...,...,...,...,...,...,...
1811,Xiaomi Redmi Note 8 4/64GB Azul Libre,Xiaomi,Redmi Note 8,4.0,64.0,Blue,Yes
1812,Xiaomi Redmi Note 8T 4/128GB Azul Estelar Libre,Xiaomi,Redmi Note 8T,4.0,128.0,Blue,Yes
1813,Xiaomi Redmi Note 9 4/128GB Blanco Libre,Xiaomi,Redmi Note 9,4.0,128.0,White,Yes
1814,Xiaomi Redmi Note 9S 4/64GB Dual SIM Gris Libre,Xiaomi,Note 9S,4.0,64.0,Gray,Yes
1815,Xiaomi Redmi Note 9S 6/128GB Dual SIM Gris Libre,Xiaomi,Note 9S,6.0,128.0,Gray,Yes